version: '3.8'

services:
  web:
    build: ./projetoevent
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/pi/Desktop/Catraca/projeto-joga-pro/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=projetojogapro
    ports:
      - 5432:5432

  # django q cluster
  djangoq:
    build: ./projetoevent
    command: python manage.py qcluster
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:


