# Generated by Django 4.0.3 on 2022-03-14 03:23

from datetime import timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_running', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('rfid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('gate', models.IntegerField()),
                ('sector', models.IntegerField()),
                ('block', models.CharField(max_length=100)),
                ('row', models.CharField(max_length=100)),
                ('seat', models.IntegerField()),
                ('extra', models.IntegerField()),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projetoevent.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('action', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(
                    auto_now_add=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True)),
                ('event_id', models.IntegerField()),
            ],
        ),
    ]
